[2025-07-20T11:03:50.515+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: retail_sales_pipeline.simulate_kafka_events manual__2025-07-20T11:02:51+00:00 [queued]>
[2025-07-20T11:03:50.533+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: retail_sales_pipeline.simulate_kafka_events manual__2025-07-20T11:02:51+00:00 [queued]>
[2025-07-20T11:03:50.534+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-20T11:03:50.534+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-20T11:03:50.534+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-20T11:03:50.559+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): simulate_kafka_events> on 2025-07-20 11:02:51+00:00
[2025-07-20T11:03:50.564+0000] {standard_task_runner.py:55} INFO - Started process 216 to run task
[2025-07-20T11:03:50.568+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'retail_sales_pipeline', 'simulate_kafka_events', 'manual__2025-07-20T11:02:51+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/retail_sales_pipeline.py', '--cfg-path', '/tmp/tmpusmoz67e']
[2025-07-20T11:03:50.569+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask simulate_kafka_events
[2025-07-20T11:03:50.882+0000] {task_command.py:389} INFO - Running <TaskInstance: retail_sales_pipeline.simulate_kafka_events manual__2025-07-20T11:02:51+00:00 [running]> on host f9ea58185622
[2025-07-20T11:03:51.207+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=retail_sales_pipeline
AIRFLOW_CTX_TASK_ID=simulate_kafka_events
AIRFLOW_CTX_EXECUTION_DATE=2025-07-20T11:02:51+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-20T11:02:51+00:00
[2025-07-20T11:03:51.208+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-20T11:03:51.209+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        python3 /opt/***/scripts/ingestion/kafka_producer.py\n        ']
[2025-07-20T11:03:51.219+0000] {subprocess.py:86} INFO - Output:
[2025-07-20T11:04:17.241+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-20T11:04:17.269+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 216. PIDs of all processes in the group: [217, 218, 216]
[2025-07-20T11:04:17.271+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 216
[2025-07-20T11:04:17.299+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-20T11:04:17.314+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-07-20T11:04:17.432+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=218, status='terminated', started='11:03:50') (218) terminated with exit code None
[2025-07-20T11:04:17.629+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 191, in execute
    cwd=self.cwd,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-07-20T11:04:17.661+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_sales_pipeline, task_id=simulate_kafka_events, execution_date=20250720T110251, start_date=20250720T110350, end_date=20250720T110417
[2025-07-20T11:04:17.943+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task simulate_kafka_events (Task received SIGTERM signal; 216)
[2025-07-20T11:04:18.065+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=216, status='terminated', exitcode=1, started='11:03:49') (216) terminated with exit code 1
[2025-07-20T11:04:18.087+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=217, status='terminated', started='11:03:50') (217) terminated with exit code None
[2025-07-20T11:04:18.091+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2025-07-20T11:04:18.508+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
